-- 0003_marc_literal_fields.sql — Colonnes littérales par champ UNIMARC
-- ────────────────────────────────────────────────────────────────────────────
-- Ajoute, sur `notices`/`exemplaires`, une colonne SQL par champ UNIMARC
-- "significatif" (présent sur ≥ 0,5% des lignes de l'export Syracuse du
-- 2026-09-22), nommée exactement comme le tag$sous-champ MARC (ex. "200$a",
-- "921$c") — pour transférer une valeur du XML directement dans sa cellule,
-- sans renommage. Liste exacte : scripts/lib/marc-columns.mjs
-- (NOTICE_LITERAL_FIELDS / ITEM_LITERAL_FIELDS), source unique partagée avec
-- scripts/db-migrate-reserve.mjs — voir ce module pour le détail des deux
-- exceptions volontaires (995$* écarté, 921$c ajouté malgré sa rareté).
--
-- Un champ plus rare que ce seuil reste capturé sans perte dans la colonne
-- `raw` (jsonb, flatten() complet) — rien n'est jamais perdu, ces colonnes ne
-- sont qu'un accès direct en SQL aux champs les plus utiles.
--
-- Remplace les colonnes "notices" renommées qui n'étaient utiles qu'à la
-- source reserve_marc (titre_complement, editeur_lieu, collation_desc,
-- dimensions, langue, pays, notes) et la table de jonction
-- contributeurs/notice_contributeurs (auteurs 700/701/702) : plus rien n'en
-- dépend en aval (export-inventaire.mjs reconstruit déjà data/inventaire.json
-- depuis la colonne `raw`, jamais depuis ces colonnes/tables), et les
-- colonnes littérales "700$a"/"700$b"/… les remplacent avec plus de
-- fidélité (auteurs multiples joints par §, comme dans data/inventaire.json).
-- Les colonnes partagées avec les sources bib_xml/excel_import (titre,
-- editeur_nom, editeur_date, isbn, issn, auteur_principal, cote_1/2/3,
-- piege_*, etat_*, section_*, bibliotheque_*) restent inchangées.
--
-- Idempotent (ADD/DROP COLUMN IF [NOT] EXISTS, DROP TABLE IF EXISTS), comme
-- 0001_init.sql/0002_livres_spolies.sql.

-- ── Table de jonction auteurs (remplacée par les colonnes 700$*/701$*/702$*
--    littérales ci-dessous) ────────────────────────────────────────────────
DROP TABLE IF EXISTS notice_contributeurs;
DROP TABLE IF EXISTS contributeurs;

-- ── Colonnes "notices" désormais redondantes (reserve_marc uniquement,
--    remplacées par les colonnes littérales) ────────────────────────────────
ALTER TABLE notices
  DROP COLUMN IF EXISTS titre_complement,
  DROP COLUMN IF EXISTS editeur_lieu,
  DROP COLUMN IF EXISTS collation_desc,
  DROP COLUMN IF EXISTS dimensions,
  DROP COLUMN IF EXISTS langue,
  DROP COLUMN IF EXISTS pays,
  DROP COLUMN IF EXISTS notes;

-- ── Colonne "exemplaires" désormais redondante (reserve_marc uniquement,
--    remplacée par "920$d") ─────────────────────────────────────────────────
ALTER TABLE exemplaires
  DROP COLUMN IF EXISTS date_entree;

-- ── Colonnes littérales, une par champ UNIMARC significatif ────────────────
ALTER TABLE notices
  ADD COLUMN IF NOT EXISTS "010$a" text,
  ADD COLUMN IF NOT EXISTS "010$b" text,
  ADD COLUMN IF NOT EXISTS "010$d" text,
  ADD COLUMN IF NOT EXISTS "010$z" text,
  ADD COLUMN IF NOT EXISTS "020$a" text,
  ADD COLUMN IF NOT EXISTS "020$b" text,
  ADD COLUMN IF NOT EXISTS "021$a" text,
  ADD COLUMN IF NOT EXISTS "021$b" text,
  ADD COLUMN IF NOT EXISTS "033$a" text,
  ADD COLUMN IF NOT EXISTS "035$5" text,
  ADD COLUMN IF NOT EXISTS "035$a" text,
  ADD COLUMN IF NOT EXISTS "035$z" text,
  ADD COLUMN IF NOT EXISTS "073$a" text,
  ADD COLUMN IF NOT EXISTS "100$a" text,
  ADD COLUMN IF NOT EXISTS "101$2" text,
  ADD COLUMN IF NOT EXISTS "101$a" text,
  ADD COLUMN IF NOT EXISTS "101$c" text,
  ADD COLUMN IF NOT EXISTS "102$a" text,
  ADD COLUMN IF NOT EXISTS "105$a" text,
  ADD COLUMN IF NOT EXISTS "106$a" text,
  ADD COLUMN IF NOT EXISTS "140$a" text,
  ADD COLUMN IF NOT EXISTS "141$a" text,
  ADD COLUMN IF NOT EXISTS "181$2" text,
  ADD COLUMN IF NOT EXISTS "181$6" text,
  ADD COLUMN IF NOT EXISTS "181$a" text,
  ADD COLUMN IF NOT EXISTS "181$b" text,
  ADD COLUMN IF NOT EXISTS "181$c" text,
  ADD COLUMN IF NOT EXISTS "182$2" text,
  ADD COLUMN IF NOT EXISTS "182$6" text,
  ADD COLUMN IF NOT EXISTS "182$a" text,
  ADD COLUMN IF NOT EXISTS "182$c" text,
  ADD COLUMN IF NOT EXISTS "183$2" text,
  ADD COLUMN IF NOT EXISTS "183$6" text,
  ADD COLUMN IF NOT EXISTS "183$a" text,
  ADD COLUMN IF NOT EXISTS "200$a" text,
  ADD COLUMN IF NOT EXISTS "200$b" text,
  ADD COLUMN IF NOT EXISTS "200$d" text,
  ADD COLUMN IF NOT EXISTS "200$e" text,
  ADD COLUMN IF NOT EXISTS "200$f" text,
  ADD COLUMN IF NOT EXISTS "200$g" text,
  ADD COLUMN IF NOT EXISTS "200$h" text,
  ADD COLUMN IF NOT EXISTS "200$i" text,
  ADD COLUMN IF NOT EXISTS "200$v" text,
  ADD COLUMN IF NOT EXISTS "205$a" text,
  ADD COLUMN IF NOT EXISTS "210$a" text,
  ADD COLUMN IF NOT EXISTS "210$b" text,
  ADD COLUMN IF NOT EXISTS "210$c" text,
  ADD COLUMN IF NOT EXISTS "210$d" text,
  ADD COLUMN IF NOT EXISTS "210$e" text,
  ADD COLUMN IF NOT EXISTS "210$f" text,
  ADD COLUMN IF NOT EXISTS "210$g" text,
  ADD COLUMN IF NOT EXISTS "210$h" text,
  ADD COLUMN IF NOT EXISTS "210$r" text,
  ADD COLUMN IF NOT EXISTS "210$s" text,
  ADD COLUMN IF NOT EXISTS "211$a" text,
  ADD COLUMN IF NOT EXISTS "214$a" text,
  ADD COLUMN IF NOT EXISTS "214$b" text,
  ADD COLUMN IF NOT EXISTS "214$c" text,
  ADD COLUMN IF NOT EXISTS "214$d" text,
  ADD COLUMN IF NOT EXISTS "214$r" text,
  ADD COLUMN IF NOT EXISTS "215$a" text,
  ADD COLUMN IF NOT EXISTS "215$c" text,
  ADD COLUMN IF NOT EXISTS "215$d" text,
  ADD COLUMN IF NOT EXISTS "215$e" text,
  ADD COLUMN IF NOT EXISTS "225$a" text,
  ADD COLUMN IF NOT EXISTS "225$e" text,
  ADD COLUMN IF NOT EXISTS "225$i" text,
  ADD COLUMN IF NOT EXISTS "225$v" text,
  ADD COLUMN IF NOT EXISTS "225$x" text,
  ADD COLUMN IF NOT EXISTS "300$a" text,
  ADD COLUMN IF NOT EXISTS "303$a" text,
  ADD COLUMN IF NOT EXISTS "305$a" text,
  ADD COLUMN IF NOT EXISTS "307$a" text,
  ADD COLUMN IF NOT EXISTS "310$a" text,
  ADD COLUMN IF NOT EXISTS "316$5" text,
  ADD COLUMN IF NOT EXISTS "316$a" text,
  ADD COLUMN IF NOT EXISTS "317$5" text,
  ADD COLUMN IF NOT EXISTS "317$a" text,
  ADD COLUMN IF NOT EXISTS "320$a" text,
  ADD COLUMN IF NOT EXISTS "321$a" text,
  ADD COLUMN IF NOT EXISTS "327$a" text,
  ADD COLUMN IF NOT EXISTS "330$2" text,
  ADD COLUMN IF NOT EXISTS "330$a" text,
  ADD COLUMN IF NOT EXISTS "345$a" text,
  ADD COLUMN IF NOT EXISTS "345$b" text,
  ADD COLUMN IF NOT EXISTS "410$3" text,
  ADD COLUMN IF NOT EXISTS "410$c" text,
  ADD COLUMN IF NOT EXISTS "410$d" text,
  ADD COLUMN IF NOT EXISTS "410$t" text,
  ADD COLUMN IF NOT EXISTS "410$v" text,
  ADD COLUMN IF NOT EXISTS "410$x" text,
  ADD COLUMN IF NOT EXISTS "454$t" text,
  ADD COLUMN IF NOT EXISTS "461$3" text,
  ADD COLUMN IF NOT EXISTS "461$t" text,
  ADD COLUMN IF NOT EXISTS "461$v" text,
  ADD COLUMN IF NOT EXISTS "464$a" text,
  ADD COLUMN IF NOT EXISTS "464$f" text,
  ADD COLUMN IF NOT EXISTS "464$t" text,
  ADD COLUMN IF NOT EXISTS "481$3" text,
  ADD COLUMN IF NOT EXISTS "481$t" text,
  ADD COLUMN IF NOT EXISTS "482$3" text,
  ADD COLUMN IF NOT EXISTS "482$5" text,
  ADD COLUMN IF NOT EXISTS "482$a" text,
  ADD COLUMN IF NOT EXISTS "482$b" text,
  ADD COLUMN IF NOT EXISTS "482$c" text,
  ADD COLUMN IF NOT EXISTS "482$t" text,
  ADD COLUMN IF NOT EXISTS "500$3" text,
  ADD COLUMN IF NOT EXISTS "500$a" text,
  ADD COLUMN IF NOT EXISTS "500$k" text,
  ADD COLUMN IF NOT EXISTS "500$m" text,
  ADD COLUMN IF NOT EXISTS "503$a" text,
  ADD COLUMN IF NOT EXISTS "503$j" text,
  ADD COLUMN IF NOT EXISTS "503$m" text,
  ADD COLUMN IF NOT EXISTS "503$n" text,
  ADD COLUMN IF NOT EXISTS "517$a" text,
  ADD COLUMN IF NOT EXISTS "600$2" text,
  ADD COLUMN IF NOT EXISTS "600$3" text,
  ADD COLUMN IF NOT EXISTS "600$a" text,
  ADD COLUMN IF NOT EXISTS "600$b" text,
  ADD COLUMN IF NOT EXISTS "600$c" text,
  ADD COLUMN IF NOT EXISTS "600$f" text,
  ADD COLUMN IF NOT EXISTS "600$x" text,
  ADD COLUMN IF NOT EXISTS "601$3" text,
  ADD COLUMN IF NOT EXISTS "601$a" text,
  ADD COLUMN IF NOT EXISTS "601$c" text,
  ADD COLUMN IF NOT EXISTS "601$x" text,
  ADD COLUMN IF NOT EXISTS "606$!" text,
  ADD COLUMN IF NOT EXISTS "606$2" text,
  ADD COLUMN IF NOT EXISTS "606$3" text,
  ADD COLUMN IF NOT EXISTS "606$a" text,
  ADD COLUMN IF NOT EXISTS "606$x" text,
  ADD COLUMN IF NOT EXISTS "606$y" text,
  ADD COLUMN IF NOT EXISTS "606$z" text,
  ADD COLUMN IF NOT EXISTS "607$2" text,
  ADD COLUMN IF NOT EXISTS "607$3" text,
  ADD COLUMN IF NOT EXISTS "607$a" text,
  ADD COLUMN IF NOT EXISTS "607$x" text,
  ADD COLUMN IF NOT EXISTS "607$z" text,
  ADD COLUMN IF NOT EXISTS "608$2" text,
  ADD COLUMN IF NOT EXISTS "608$3" text,
  ADD COLUMN IF NOT EXISTS "608$a" text,
  ADD COLUMN IF NOT EXISTS "620$3" text,
  ADD COLUMN IF NOT EXISTS "620$a" text,
  ADD COLUMN IF NOT EXISTS "620$d" text,
  ADD COLUMN IF NOT EXISTS "676$a" text,
  ADD COLUMN IF NOT EXISTS "676$v" text,
  ADD COLUMN IF NOT EXISTS "686$2" text,
  ADD COLUMN IF NOT EXISTS "686$a" text,
  ADD COLUMN IF NOT EXISTS "700$3" text,
  ADD COLUMN IF NOT EXISTS "700$4" text,
  ADD COLUMN IF NOT EXISTS "700$a" text,
  ADD COLUMN IF NOT EXISTS "700$b" text,
  ADD COLUMN IF NOT EXISTS "700$c" text,
  ADD COLUMN IF NOT EXISTS "700$f" text,
  ADD COLUMN IF NOT EXISTS "700$o" text,
  ADD COLUMN IF NOT EXISTS "701$3" text,
  ADD COLUMN IF NOT EXISTS "701$4" text,
  ADD COLUMN IF NOT EXISTS "701$a" text,
  ADD COLUMN IF NOT EXISTS "701$b" text,
  ADD COLUMN IF NOT EXISTS "701$c" text,
  ADD COLUMN IF NOT EXISTS "701$f" text,
  ADD COLUMN IF NOT EXISTS "701$o" text,
  ADD COLUMN IF NOT EXISTS "702$3" text,
  ADD COLUMN IF NOT EXISTS "702$4" text,
  ADD COLUMN IF NOT EXISTS "702$a" text,
  ADD COLUMN IF NOT EXISTS "702$b" text,
  ADD COLUMN IF NOT EXISTS "702$c" text,
  ADD COLUMN IF NOT EXISTS "702$d" text,
  ADD COLUMN IF NOT EXISTS "702$f" text,
  ADD COLUMN IF NOT EXISTS "702$o" text,
  ADD COLUMN IF NOT EXISTS "710$3" text,
  ADD COLUMN IF NOT EXISTS "710$4" text,
  ADD COLUMN IF NOT EXISTS "710$a" text,
  ADD COLUMN IF NOT EXISTS "710$c" text,
  ADD COLUMN IF NOT EXISTS "711$3" text,
  ADD COLUMN IF NOT EXISTS "711$4" text,
  ADD COLUMN IF NOT EXISTS "711$a" text,
  ADD COLUMN IF NOT EXISTS "712$3" text,
  ADD COLUMN IF NOT EXISTS "712$4" text,
  ADD COLUMN IF NOT EXISTS "712$a" text,
  ADD COLUMN IF NOT EXISTS "712$b" text,
  ADD COLUMN IF NOT EXISTS "712$c" text,
  ADD COLUMN IF NOT EXISTS "801$2" text,
  ADD COLUMN IF NOT EXISTS "801$a" text,
  ADD COLUMN IF NOT EXISTS "801$b" text,
  ADD COLUMN IF NOT EXISTS "801$c" text,
  ADD COLUMN IF NOT EXISTS "801$g" text,
  ADD COLUMN IF NOT EXISTS "801$h" text,
  ADD COLUMN IF NOT EXISTS "830$a" text,
  ADD COLUMN IF NOT EXISTS "856$u" text,
  ADD COLUMN IF NOT EXISTS "900$a" text,
  ADD COLUMN IF NOT EXISTS "901$a" text,
  ADD COLUMN IF NOT EXISTS "902$3" text,
  ADD COLUMN IF NOT EXISTS "902$a" text,
  ADD COLUMN IF NOT EXISTS "902$e" text,
  ADD COLUMN IF NOT EXISTS "917$a" text,
  ADD COLUMN IF NOT EXISTS "919$a" text,
  ADD COLUMN IF NOT EXISTS "940$a" text,
  ADD COLUMN IF NOT EXISTS "940$b" text,
  ADD COLUMN IF NOT EXISTS "940$s" text;
ALTER TABLE exemplaires
  ADD COLUMN IF NOT EXISTS "202$a" text,
  ADD COLUMN IF NOT EXISTS "202$d" text,
  ADD COLUMN IF NOT EXISTS "316$a" text,
  ADD COLUMN IF NOT EXISTS "915$a" text,
  ADD COLUMN IF NOT EXISTS "915$b" text,
  ADD COLUMN IF NOT EXISTS "920$d" text,
  ADD COLUMN IF NOT EXISTS "920$e" text,
  ADD COLUMN IF NOT EXISTS "920$r" text,
  ADD COLUMN IF NOT EXISTS "920$s" text,
  ADD COLUMN IF NOT EXISTS "920$t" text,
  ADD COLUMN IF NOT EXISTS "920$u" text,
  ADD COLUMN IF NOT EXISTS "921$a" text,
  ADD COLUMN IF NOT EXISTS "921$b" text,
  ADD COLUMN IF NOT EXISTS "921$c" text,
  ADD COLUMN IF NOT EXISTS "930$b" text,
  ADD COLUMN IF NOT EXISTS "930$c" text,
  ADD COLUMN IF NOT EXISTS "930$d" text,
  ADD COLUMN IF NOT EXISTS "930$g" text,
  ADD COLUMN IF NOT EXISTS "930$h" text,
  ADD COLUMN IF NOT EXISTS "930$i" text;

-- ── Journal des rafraîchissements (refresh) ─────────────────────────────────
-- Une ligne par exécution de scripts/db-migrate-reserve.mjs (et, même forme,
-- réutilisable par les autres scripts db-migrate-*.mjs). `admin.html` affiche
-- la ligne la plus récente par `source` — la date à indiquer côté Syracuse
-- pour n'exporter que les notices modifiées depuis (`started_at`, capturé
-- avant la moindre lecture du XML : un léger recouvrement avec la prochaine
-- fenêtre d'export est sans risque — une notice réexportée deux fois se
-- réapplique à l'identique — alors qu'une date prise après coup risquerait
-- de sauter des modifications survenues pendant le traitement).
CREATE TABLE IF NOT EXISTS sync_runs (
  id                  bigserial PRIMARY KEY,
  source              text NOT NULL,   -- 'reserve_marc', 'bib_xml', …
  started_at          timestamptz NOT NULL,
  finished_at         timestamptz,
  notices_upserted    integer,
  exemplaires_upserted integer,
  status              text NOT NULL DEFAULT 'ok' CHECK (status IN ('ok', 'error')),
  error_message       text
);
CREATE INDEX IF NOT EXISTS idx_sync_runs_source_started ON sync_runs (source, started_at DESC);
